server:
  port: 8050

spring:
  profiles:
    active: prod

api:
  prefix: /api/product

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always